/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package greeter;

public class App {

    public static void main(String[] args) {
        final String output = GreetingFormatter.greeting(args[0]);
        System.out.println(output);
    }

    public String getGreeting() {
        return "hello world";
    }
}
